blank_issues_enabled: false
contact_links:
  - name: Have a question or need help?
    url: https://github.com/nosebit/simian/discussions
    about: Ask questions and discuss with the community in GitHub Discussions.
