name: 🚀 Feature Request
description: Propose a new feature for Swini
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you so much for suggesting a new feature for Swini 🐷!
  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
      description:
        A clear and concise description of what the problem is. Ex. I'm always
        frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: How will this feature solve the problem?
      description: A clear and concise description of is expected to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives were considered?
      description:
        A clear and concise description of any alternative solutions or features
        that have being considered before opening this request.
