syntax = "proto3";

package swini.croft;

service CroftApi {
  rpc Join(JoinReq) returns (JoinRes);
  rpc Status(StatusReq) returns (StatusRes);
}

message JoinReq {
  uint64 id = 1;
  string name = 2;
  string addr = 3;
  repeated string roles = 4;
  repeated string tags = 5;
}

message JoinRes {
  repeated Croft server_crofts = 1;
}

message StatusReq {}

message StatusRes {
  repeated Croft crofts = 1;
  uint64 primary_id = 2;
}

message Croft {
  uint64 id = 1;
  string name = 2;
  string addr = 3;
  repeated string roles = 4;
  repeated string tags = 5;
  string joined_at = 6;
  bool is_primary = 7;
}
